[local]
name = "bishop"
port = 9091
httpServerPort = 8081
logInterval = 2500
ackTimeout = 1000
antiEntropyInterval = 10000

[peers]

  [peers.queen]
  hostname = "peer1"
  port = 9090

  [peers.knight]
  hostname = "peer3"
  port = 9092

  [peers.rook]
  hostname = "peer4"
  port = 9093

  [peers.pawn]
  hostname = "peer5"
  port = 9094
